---

- name: Obtain the version of the running PowerDNS instance
  shell: |
    pdns_server --version 2>&1 | grep -o "PowerDNS Authoritative Server.*" | awk '{print $4}'
  register: _pdns_version
  check_mode: no
  changed_when: False

- name: Export the running PowerDNS instance version to a variable
  set_fact:
    _pdns_running_version: "{{ _pdns_version['stdout'] | regex_replace('-[.\\d\\w]+$', '') }}"
